package SwingUI;


import DAO.ÜrünlerDAO;
import AbstractDal.JDBCBaglanti;
import DAO.Veritabanı;
import java.awt.HeadlessException;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

public class ÜrünSil extends javax.swing.JFrame {
    
    Connection con;
    ResultSet rs;
    PreparedStatement prs;
    Statement st;
    String dbUrl = "jdbc:mysql://localhost:3306/stoktakipotomasyonu";
    ÜrünlerDAO islemler =  new ÜrünlerDAO();
    Veritabanı veritabanı = new Veritabanı();
    
    
    JDBCBaglanti jDBCBaglanti = new JDBCBaglanti() {

        @Override
        public String connectionStatus() throws SQLException {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    };
    public ÜrünSil() throws SQLException{
        initComponents();
        databaseBaglanti();
        ürünSilTablo();
        this.setLocationRelativeTo(null);

    }
    
    public void databaseBaglanti() {
        try {
            con =  DriverManager.getConnection(dbUrl, "root", "");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Veritabanı Bağlantısı Başarısız Oldu...");
        }
    }
    
    
    public void ürünSilTablo() {
        try {
            String sql = "select id as Id ,ürün_adi as Ürün_Adi,ürün_kategorisi as Ürün_Kategorisi,ürün_stok as Ürün_Stok,"
                    + "ürün_af as Ürün_Alış_Fiyatı,ürün_sf as Ürün_Satış_Fiyatı from ürünler order by ürün_kategorisi asc";
            prs = con.prepareStatement(sql);
            rs = prs.executeQuery();
            ürünSilTablo.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ürünSilTablo = new javax.swing.JTable();
        sıralaText = new javax.swing.JTextField();
        sıralaCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        ürünSilButton = new javax.swing.JButton();
        ürünSilId = new javax.swing.JLabel();
        ürünSilAd = new javax.swing.JLabel();
        ürünSilKategori = new javax.swing.JLabel();
        ürünSilStok = new javax.swing.JLabel();
        ürünSilAlısFiyatı = new javax.swing.JLabel();
        ürünSilSatısFiyatı = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ürün Sil\n");

        jLabel1.setText("ID");

        jLabel2.setText("Ürün Adı");

        jLabel3.setText("Ürün Kategori");

        jLabel4.setText("Stok");

        jLabel5.setText("Alış Fiyatı");

        jLabel6.setText("Satış Fiyatı");

        ürünSilTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ürünSilTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ürünSilTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ürünSilTablo);

        sıralaText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sıralaTextKeyPressed(evt);
            }
        });

        sıralaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ürün Kategorisine Göre", "Ürün İsmine Göre", "Stok Miktarına Göre Düşükten Yükseğe", "Stok Miktarına Göre Yüksekten Düşüğe" }));
        sıralaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sıralaComboActionPerformed(evt);
            }
        });

        jLabel7.setText("Ara");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(sıralaText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(sıralaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sıralaText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sıralaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        ürünSilButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ürünsil.png"))); // NOI18N
        ürünSilButton.setText("Ürün Sil");
        ürünSilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürünSilButtonActionPerformed(evt);
            }
        });

        ürünSilId.setText("-");

        ürünSilAd.setText("-");

        ürünSilKategori.setText("-");

        ürünSilStok.setText("-");

        ürünSilAlısFiyatı.setText("-");

        ürünSilSatısFiyatı.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ürünSilId)
                                        .addComponent(ürünSilAd)
                                        .addComponent(ürünSilKategori))
                                    .addComponent(ürünSilStok, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ürünSilSatısFiyatı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ürünSilAlısFiyatı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(ürünSilButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ürünSilId))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ürünSilAd))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(ürünSilKategori)))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ürünSilStok))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ürünSilAlısFiyatı))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ürünSilSatısFiyatı)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ürünSilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ürünSilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürünSilButtonActionPerformed
        int onay = JOptionPane.showConfirmDialog(null, "Ürün Silinecek Onaylıyor Musunuz ?", "Onaylıyor Musunuz ?", HEIGHT);
        if (onay == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.valueOf(ürünSilId.getText());
                 String ürünAdi = ürünSilAd.getText().trim();
                String kategori =ürünSilKategori.getText().trim();
                String adet = ürünSilStok.getText().trim();
                String alısFiyatı = ürünSilAlısFiyatı.getText().trim();
                String satisFiyati = ürünSilSatısFiyatı.getText().trim();

                islemler.ürünSil(id,ürünAdi, kategori, adet, alısFiyatı, satisFiyati);
                
                 ürünSilTablo();
                ürünSilAd.setText("-");
                ürünSilKategori.setText("-");
                ürünSilStok.setText("-");
                ürünSilAlısFiyatı.setText("-");
                ürünSilSatısFiyatı.setText("-");
               
            } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Hata");
        }
        }
                                      

    }//GEN-LAST:event_ürünSilButtonActionPerformed

    private void ürünSilTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ürünSilTabloMouseClicked
         try {
            int row = ürünSilTablo.getSelectedRow();
            String tableClick = (ürünSilTablo.getModel().getValueAt(row, 0).toString());
            String sqlString = "select * from ürünler where id='" + tableClick + "'  ";
            prs = con.prepareStatement(sqlString);
            rs = prs.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("ürün_adi");
                ürünSilAd.setText(add1);
                String add2 = rs.getString("ürün_kategorisi");
                ürünSilKategori.setText(add2);
                String add3 = rs.getString("ürün_stok");
                ürünSilStok.setText(add3);
                String add4 = rs.getString("ürün_af");
                ürünSilAlısFiyatı.setText(add4);
                String add5 = rs.getString("ürün_sf");
                ürünSilSatısFiyatı.setText(add5);
                String add6 = rs.getString("id");
                ürünSilId.setText(add6);
              
            
                
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ürünSilTabloMouseClicked

    private void sıralaTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sıralaTextKeyPressed
       TableRowSorter<TableModel> sorter = new TableRowSorter<>((DefaultTableModel) ürünSilTablo.getModel());
        sorter.setRowFilter(RowFilter.regexFilter(this.sıralaText.getText()));
        ürünSilTablo.setRowSorter(sorter);
        ürünSilTablo();
    }//GEN-LAST:event_sıralaTextKeyPressed

    private void sıralaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sıralaComboActionPerformed
         String c = String.valueOf(sıralaCombo.getSelectedItem());
        if (c == "Ürün Grubuna Göre") {
            try {
                String sql = "select * from ürünler order by ürün_kategorisi asc";
                prs = con.prepareStatement(sql);
                rs = prs.executeQuery();
                ürünSilTablo.setModel(DbUtils.resultSetToTableModel(rs));
                ürünSilTablo.getColumnModel().getColumn(0).setMaxWidth(40);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else if (c == "Ürün İsmine Göre") {
            try {
                String sql = "select * from ürünler order by ürün_adi asc";
                prs = con.prepareStatement(sql);
                rs = prs.executeQuery();
                ürünSilTablo.setModel(DbUtils.resultSetToTableModel(rs));
                ürünSilTablo.getColumnModel().getColumn(0).setMaxWidth(40);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else if (c == "Stok Miktarına Göre Düşükten Yükseğe") {
            try {
                String sql = "select * from ürünler order by ürün_stok asc";
                prs = con.prepareStatement(sql);
                rs = prs.executeQuery();
                ürünSilTablo.setModel(DbUtils.resultSetToTableModel(rs));
                ürünSilTablo.getColumnModel().getColumn(0).setMaxWidth(40);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else if (c == "Stok Miktarına Göre Yüksekten Düşüğe") {
            try {
                String sql = "select * from ürünler order by ürün_stok desc";
                prs = con.prepareStatement(sql);
                rs = prs.executeQuery();
                ürünSilTablo.setModel(DbUtils.resultSetToTableModel(rs));
                ürünSilTablo.getColumnModel().getColumn(0).setMaxWidth(40);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_sıralaComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÜrünSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÜrünSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÜrünSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÜrünSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ÜrünSil().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ÜrünSil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox sıralaCombo;
    private javax.swing.JTextField sıralaText;
    private javax.swing.JLabel ürünSilAd;
    private javax.swing.JLabel ürünSilAlısFiyatı;
    private javax.swing.JButton ürünSilButton;
    private javax.swing.JLabel ürünSilId;
    private javax.swing.JLabel ürünSilKategori;
    private javax.swing.JLabel ürünSilSatısFiyatı;
    private javax.swing.JLabel ürünSilStok;
    private javax.swing.JTable ürünSilTablo;
    // End of variables declaration//GEN-END:variables
}
